version: 2.1

jobs:
  build:
    working_directory: /frontend2
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: build docker image
        command: docker build -t app .
